required:
  - type
  - text
properties:
  type:
    type: string
    description: The action type.
    enum:
      - link
      - buy
      - postback
      - reply
      - locationRequest
  text:
    type: string
    description: The button text.
  payload:
    type: string
    description: |
      The payload to be sent with the resulting webhook.
      Required for *postback* and *reply* actions.
  metadata:
    type: object
    description: >-
      Flat JSON object containing any custom properties associated with the
      action.
  amount:
    type: integer
    description: >
      The amount being charged. It needs to be specified in cents and is an
      integer.

      Required for *buy* actions.
  currency:
    type: string
    description: 'The currency of the amount being charged (USD, CAD, etc.).'
  default:
    type: boolean
    description: >-
      Flag indicating if the message action is the default for a message item in
      Facebook Messenger.
  iconUrl:
    type: string
    description: >-
      An icon to render next to the reply option (Facebook Messenger and Web
      Messenger only).
  uri:
    type: string
    description: >
      The action URI. This is the link that will be used in the clients when
      clicking the button.

      Required for *link* actions.
